### PR TITLE
feat: Show link to website if no phone present

### PR DESCRIPTION
**Pull request by Jaszkowic**
Tested manually by mocking data, all entries in prod data do have phone numbers right now.  

Bildschirmfoto 2023-08-07 um 09 45 03

### CODE REVIEW

**Comment by Jaszkowic** [comment]
@vogelino 

- Not sure if we want to open the link in new tab?
- Do we want to have a link icon? I didn't want to use the "Globe" icon, because it is already used for the language field

**Comment by Jaszkowic** [comment]
Some facilities (i found one -> "Teilhabefachdienst Friedrichshain-Kreuzberg") also have "_keine_" as phone number -> Should we include this on code level? I would vote for cleaning up the data instead.

**Comment by vogelino** [comment]
> * Not sure if we want to open the link in new tab?

According to [this post](https://uxdesign.cc/linking-to-a-new-tab-vs-same-tab-f88b495d2187?gi=a11ed95deced), I think it makes sense to open those links on the same page (no new tab). I tend to agree, we are not a marketing page attempting to maintain the users on our page. If users want to open it in a new tab the can do this explicitly.

> * Do we want to have a link icon?

I think it is indeed a good idea. I'm not sure about the globe as a symbol for languages but that's another debate. A link icon would work fine here anyway. 

PS: I think we are using[ feather icons here](https://feathericons.com/?query=link)

**Review by vogelino — DISMISSED** [review]
Outside of the comments above, good work! :) Merge it when you added the icon if there is no major additional change. IMHO looks goot like this.

**Comment by Jaszkowic** [comment]
External link icon added:

image

**Pull request merged**
