### PR TITLE
fix(WEG-134): Show selected item as well as user location

### PR DESCRIPTION
**Pull request by vogelino**
This PR:
- Adds a user geolocation marker and zooms in the map when geolocation is activated
- Refactors the display of the current facility's marker

### CODE REVIEW

**Review by dnsos — COMMENTED** [review]
Great solution that works very well!

I was wondering one thing (and feel free to ignore): MapLibre provides the [`GeolocateControl`](https://maplibre.org/maplibre-gl-js-docs/api/markers/#geolocatecontrol) which we are not using here. I _think_ that our custom solution will behave the same: Even when moving around, the location indicator would be rerendered, right? My argument for prefering `GeolocateControl` is that it's less code to maintain when we use the built-in solution. What do you think?

**Comment by vogelino** [comment]
So @dnsos ! I was able to add a geolocate control to show the current user position (Which is cool because it uses the native geolocate pulsing geo marker). My problem is that there are no efficient way to disable it once activated. You can remove the marker, but it only work when you start with a deactivated proximity filter which is then activated. Once deactivated and then reactivated, it doesn't work anymore. I'm sure there would be a way to fix that but honestly, the code starts to get even more complex that the one we have currently. I think it is fine to keep the current implementation. Let me know what you think. We can also have a call.

**Review by dnsos — APPROVED** [review]
@vogelino thanks for trying! I'm not surprised that there might be some conflicting things happening when mixing. So I agree that in this case it's better to stick with our solution (which is good!) rather than enforcing a mix of both.

**Pull request merged**
