### PR TITLE
feat: Use cache data for initial build

### PR DESCRIPTION
**Pull request by vogelino**
This PR downloads all the data initially on build time as json and uses this to render the pages statically. This avoids getting _429 too many requests_ responses. Then, if the data changes, the revalidate of nextjs executes and it fetches the real data, not the jsons.

#42 should be merged before this branch.

A great little hack! :)

### CODE REVIEW

**Review by dnsos — APPROVED** [review]
Great solution for this issue 👍 Nothing to add from my side.

Just a hint if anyone else looks at this PR: If we want to test the build script locally, a `env.local.development` is not sufficient. We need to additionally add a `.env` with all required variables for the build script to pick it up.

**Comment by vogelino** [comment]
> Just a hint if anyone else looks at this PR: If we want to test the build script locally, a `env.local.development` is not sufficient. We need to additionally add a `.env` with all required variables for the build script to pick it up.

True! I added a hint in the readme

**Pull request merged**
