### PR TITLE
refactor(WEG-131): Change appearance of location switch to impr. ux

### PR DESCRIPTION
**Pull request by vogelino**
People were confused about the location switch and didn't know when it was on or off. 
This is the new look of the location switch:

https://user-images.githubusercontent.com/2759340/202417669-27da7fdf-2fce-46ab-b7a6-1e9bee115c52.mov

### CODE REVIEW

**Review by dnsos — COMMENTED** [review]
Straightforward changes, good work!

However, I am not sure whether this change is necessary. If we need to change the visual language of the whole page, the change to rounded corners may work. But with the current CI requirements, I am hesitant to deviate from the defined toggle style. Rounded corners seem like a pretty strong contrast to the otherwise sharp edges.

**Comment by vogelino** [comment]
Thx for the review!

> I am not sure whether this change is necessary. If we need to change the visual language of the whole page, the change to rounded corners may work. But with the current CI requirements, I am hesitant to deviate from the defined toggle style. Rounded corners seem like a pretty strong contrast to the otherwise sharp edges.

These are the results of the user tests. Many people were apparently confused with this UI element. I think that switches are most commonly round and this appearance is more recognizable for most. I don't think however that this means we need to change the whole UI language. UX has priority over UI-language consistency. But we could discuss that again it you'd like. I'd be curious about @edgalindo's opinion on that too. How strict should we be about following Berlin's guide if the UX tests show some difficulties with it?

**Comment by dnsos** [comment]
> I think that switches are most commonly round and this appearance is more recognizable for most

Totally agree with that!

I am under the assumption that the CI guide (and the toggle) has been tested thoroughly for UX, perhaps invalidating our rather small-scoped tests. But then again, this is an _assumption_, so I actually don't have much of an argument here, and personally also agree that the new toggle is clearer.

**Comment by vogelino** [comment]
> I am under the assumption that the CI guide (and the toggle) has been tested thoroughly for UX

I'm not sure about that. The company that developed the CI-guidelines isn't specialized in UX and I would bet that thorough UX tests have been done. Or are you aware of some tests and where can I find more about it?

**Comment by dnsos** [comment]
> Or are you aware of some tests and where can I find more about it?

No, absolutely not. That's why I think my initial concern is not really valid. From my side this can be merged.

**Pull request merged**
