### PR TITLE
refactor(WEG-110): Improve display of tags in the interface

### PR DESCRIPTION
**Pull request by vogelino**
**New solution:** We show only the tags as text, always highlighted red when active (in all views). To avoid that the list of all tags becomes too high when there are too many cards (especially in the card view), we show in this case the active ones followed by "and all other topics". See screenshots:
| image_2022-11-24_110939293 | image_2022-11-24_111025103 | image_2022-11-24_111044814 | image_2022-11-24_111120006 |
|--|--|--|--|

### CODE REVIEW

**Comment by vogelino** [comment]
@dnsos I added the changes discussed yesterday including:
- Unifying the appearance of labels in all views
- Adding the "and all others" and "all" to target audience labels too
- Remove "and all others" when all filters are selected

**Review by dnsos — APPROVED** [review]
Good changes as well as the refactorings! Don't have anything to add here - well done!

**Pull request merged**
