### PR TITLE
feat(WEG-160): phone number parser

### PR DESCRIPTION
**Pull request by dnsos**
This PR makes sure that only the first phone number is displayed for a facility, even though some facilities have multiple phone numbers in the backend table.

### CODE REVIEW

**Comment by vogelino** [comment]
Are you sure that this is thé intended behavior? I thought that both phone numbers were supposed to show up. Maybe I got it wrong.

**Comment by dnsos** [comment]
> Are you sure that this is thé intended behavior?

It was my understanding, yes. But I will double-check that.

**Comment by vogelino** [comment]
Ok! If I'm wrong, ship it! :)

**Comment by dnsos** [comment]
@vogelino would you take another look? We are now displaying all phone numbers. I have opted for simply displaying a new row for each phone number, because we had the previous requirement that the icons should be clickable as well. That's why I would suggest adding the new row as opposed to having 2 or 3 phone numbers in one row with one icon.

Screenshot 2023-01-31 at 11 29 23

**Comment by vogelino** [comment]
> @vogelino would you take another look? 

Great! That makes it very handy! Well done!

**Review by vogelino — APPROVED** [review]

**Pull request merged**
