### PR TITLE
feat(WEG-169): restrict to one focus group

### PR DESCRIPTION
**Pull request by dnsos**
This PR refactors the focus group selection from a checkbox behaviour to a radio group behaviour.

Open todo's:

- [x] figure out why "reset" button doesn't reset visual state of radio group properly
- [x] check whether "changing from uncontrolled to controlled" component is an issue (we can have an undefined focus group)

### CODE REVIEW

**Review by vogelino — APPROVED** [review]
Great work! Very clean and accessible! My only wish would be to make the radio buttons toggable. I know that you can click on "Zurücksetzen" but I would expect to deactivate a radio-filter when I click it again. Feel free to ignore if you're against it. Good job!

**Comment by dnsos** [comment]
@vogelino I'm not against it and I have taken a look at it.

Unfortunately, the `RadioGroup` from Headless UI doesn't emit an `onChange` event when the same option is clicked that is already selected (which logically makes sense since nothing has "changed"). Therefore there is no event to work with that could deselect the current selection. There are probably ways to work around it, but I think that this would include major changes. So, in my opinion the toggle functionality is not worth the unknown time investment.

**Comment by vogelino** [comment]
> @vogelino I'm not against it and I have taken a look at it.
> 
> Unfortunately, the `RadioGroup` from Headless UI doesn't emit an `onChange` event when the same option is clicked that is already selected (which logically makes sense since nothing has "changed"). Therefore there is no event to work with that could deselect the current selection. There are probably ways to work around it, but I think that this would include major changes. So, in my opinion the toggle functionality is not worth the unknown time investment.

I agree it might not be worth the effort. To be honest though, I'm not sure why using headless ui for this was necessary instead of using the aria labels directly. This way we could decide ourselves how the ux should be and are not making decisions based on the library. Also we wouldn't have an additional dependency just for a radio behavior. But I don't want to overcomplicate everything now. Just some thoughts on which I'd like your opinion. Feel free to merge!

**Comment by dnsos** [comment]
The decision for Headless UI was because I see it as an important asset for accessibility. Their components seem to be well-crafted and I expect them to be maintained for quite a while because of the wide adoption of Tailwind.

I'm assuming that our homegrown solutions might not be as qualitative accessibility-wise, thinking about all the different `aria-` stuff we'd have to handle. In contrast the lack of a toggle functionality seems acceptable to me.

**Comment by vogelino** [comment]
> I'm assuming that our homegrown solutions might not be as qualitative accessibility-wise, thinking about all the different `aria-` stuff we'd have to handle. In contrast the lack of a toggle functionality seems acceptable to me.

All right! Thx for your answer. Ship it!

**Pull request merged**
