### PR TITLE
feat(WEG-53): state in URL

### PR DESCRIPTION
**Pull request by dnsos**
This PR makes the URL query params the source of truth for the filtered tags.

- [x] add mapper function
- [x] update lat/lng/zoom on map interaction
- [x] display dots on map conditionally (_if all the URL tags are present in the facilities' Schlagworte_ -> tricky because we have to create sort of an `every` expression with MapLibre's query language)
- [x] style dots Berlin red

### CODE REVIEW

**Comment by dnsos** [comment]
@vogelino, this is ready for review now!

Can you double-check if the correct tag filters are applied to the map _without_ further interaction? I've had one or two occasions now where they actually didn't update, but I couldn't reproduce it every time.

**Comment by vogelino** [comment]
> Can you double-check if the correct tag filters are applied to the map _without_ further interaction? I've had one or two occasions now where they actually didn't update, but I couldn't reproduce it every time.

Thx! Will do!

**Review by vogelino — APPROVED** [review]
Great work! Well done with the tricky parts. I tested it as good as I could and it seems to work fine. We should try with the real filters once it's implemented though.

It seems you added the `swr` package. I just don't see where the `swr` dependency is use. Ignore if we do, please remove if we don't!

**Comment by dnsos** [comment]
> It seems you added the swr package. I just don't see where the swr dependency is use. Ignore if we do, please remove if we don't!

Actually I didn't add it, the diff visualization is bit misleading there (I added the `use-debounce` one line below). But it's true that we are not using it anymore so I have removed it!

> We should try with the real filters once it's implemented though.

👍

**Comment by vogelino** [comment]
> Actually I didn't add it, the diff visualization is bit misleading there

True! Thx anyway! :)

**Pull request merged**
