### PR TITLE
feat(WEG-63): show facilities preview when clicking circle on map

### PR DESCRIPTION
**Pull request by dnsos**
This PR adds the preview card for the facilities. Additionally it makes some adjustments to the UI elements, because some changes to the structure and the stack order were needed.

This PR will additionally close WEG-52, WEG-72, WEG-73, WEG-74.

### CODE REVIEW

**Review by vogelino — CHANGES_REQUESTED** [review]
Great work and good UI/UX! It's nearing the end at a quick pace!
I noticed a few things though:
- There is a weird behaviour on desktop, where slides can be dragged passed the slides. (See video)
- I love the repositioning of the info and emergency buttons. It makes the layout way clear. It is a little bit far from the fingers if hold from the right hand but so is the home button so I don't think this argument applies.
- I think it is a good compromise to say that the header with the filters and the home button shouldn't be displayed on an individual view. Well done
- I noticed that when you go to an individual view on desktop and then click on "zurück", that the title "300 Einrichtungen" is offset from the top. (See video 2)

**Video 1:**

https://user-images.githubusercontent.com/2759340/195539142-a9b8b605-4f04-45b8-860a-a1a337ef28db.mov



**Video 2:**

https://user-images.githubusercontent.com/2759340/195539196-18159abc-7d55-44d2-842e-b8c7aef8ad21.mov

**Comment by dnsos** [comment]
Thanks for the review, @vogelino!

Yes, I've had to make some changes on-the-go concerning what is when displayed and where. Glad that you agree with the solutions.

---

To figure out:

- [ ] check why slides can dragged too far on desktop
- [ ] check why the "X Einrichtungen" is offset from the top when clicking "Zurück" from the individual facility view

**Review by vogelino — APPROVED** [review]
Great! All problems solved! Thx!

**Pull request merged**
